FROM cyberdojofoundation/javascript-node:6df9f12
LABEL maintainer=jon@jaggersoft.com

RUN mkdir /etc/jest
WORKDIR /etc/jest
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
